version: "3.9"

services:
  api:
    image: ghcr.io/shrooml-team/automl:${IMAGE_TAG:-latest}
    container_name: automl-api
    ports:
      - "${HOST_PORT:-63002}:8000"
    volumes:
      - users_db:/app/db/
    environment:
      - SECRET_KEY=iloveshrooms
    restart: unless-stopped
    
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '8'
          memory: 8G
        reservations:
          cpus: '4'
          memory: 4G

volumes:
  users_db:
    driver: local
